# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [3]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
l=[50,60,80,100,200.300,500,600]
l

[50, 60, 80, 100, 200.3, 500, 600]

In [5]:
# Let's create a numpy array from the list "my_list"
nparr=np.array(l)
nparr

array([ 50. ,  60. ,  80. , 100. , 200.3, 500. , 600. ])

In [6]:
type(nparr)

numpy.ndarray

In [7]:
# Multi-dimensional (Matrix definition) 
my_matrix=np.array([[2,5,8],[7,3,6]])

In [8]:
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
# do here

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [10]:
# "rand()" uniform distribution between 0 and 1
x=np.random.rand(20)
x

array([0.53881838, 0.02111751, 0.33772634, 0.54140484, 0.56978404,
       0.59112184, 0.88943382, 0.24148232, 0.22290051, 0.80418595,
       0.32651728, 0.84792963, 0.97243865, 0.4370344 , 0.19357152,
       0.08960104, 0.44197397, 0.54247873, 0.59298818, 0.32795838])

In [12]:
# you can create a matrix of random number as well
x=np.random.rand(3,3)
x

array([[0.98337491, 0.00141049, 0.04254393],
       [0.40397453, 0.84138974, 0.5383247 ],
       [0.79561184, 0.49544833, 0.44714255]])

In [15]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(1,50)
x

28

In [16]:
# "randint" can be used to generate a certain number of random itegers as follows
x=np.random.randint(1,100,50) # 50 random numbers between 1 and 100
x

array([ 8, 29, 80, 54,  1,  2, 80, 36, 83, 38, 80,  6, 48,  5, 95, 69, 61,
       97, 60, 86, 80, 88, 12, 38,  6, 11, 69, 16, 85, 59, 38, 96, 14,  1,
       57, 54, 34, 79, 94,  6, 52, 27, 21, 33, 42, 89, 94, 15, 68, 34])

In [18]:
# np.arange creates an evenly spaced values within a given interval
x=np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
# create a diagonal of ones and zeros everywhere else
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [21]:
# Matrix of ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# Multidimentional Array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# Array of zeros
np.zeros(3)

array([0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
# do here

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [26]:
# np.arange() returns an evenly spaced values within a given interval
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
y=np.arange(11,20)
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
# Add 2 numpy arrays together
x+y

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [29]:
squared=x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [30]:
sqrt=np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
z=np.exp(y)
z

array([5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
       3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
       1.78482301e+08])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [ ]:
#do here

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [33]:
my_numpy_arr=np.array([3,5,6,2,8,10,20,50])
my_numpy_arr

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [34]:
# Access specific index from the numpy array
my_numpy_arr[5]

10

In [35]:
# Access last index from the numpy array
my_numpy_arr[-1]

50

In [36]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_arr[0:3]

array([3, 5, 6])

In [37]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_arr[0:4]=7

In [38]:
my_numpy_arr

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [40]:
# Let's define a two dimensional numpy array
mat=np.random.randint(1,10,(4,4))
mat

array([[4, 1, 3, 8],
       [4, 5, 5, 5],
       [7, 5, 5, 4],
       [1, 4, 4, 3]])

In [42]:
# get rows of mat
mat[0] # first row
mat[-1] # last row

array([1, 4, 4, 3])

In [43]:
# Get one element
mat[0][2] # element at first row and third column

3

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [ ]:
# do here

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [46]:
mat=np.random.randint(1,10,(5,5))
mat

array([[2, 5, 3, 9, 6],
       [8, 3, 4, 3, 4],
       [9, 7, 1, 1, 6],
       [6, 6, 4, 9, 6],
       [4, 9, 5, 5, 7]])

In [48]:
mat[mat>7] # elements that are greater than 7

array([9, 8, 9, 9, 9])

In [51]:
# Obtain odd elements only
mat[mat%2==1]

array([5, 3, 9, 3, 3, 9, 7, 1, 1, 9, 9, 5, 5, 7])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
# do here

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [52]:
import pandas as pd

In [54]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary


bank_client_df=pd.DataFrame({'Bank client id': [111,222,333,444],'Name': ['Ridham','Harman','Vishav','Puneet']})
bank_client_df

Bank client id    Name
0             111  Ridham
1             222  Harman
2             333  Vishav
3             444  Puneet

In [55]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [57]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank client id    Name
0             111  Ridham
1             222  Harman

In [58]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(1)

Bank client id    Name
3             444  Puneet

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
# do here

In [ ]:
# pandas with html data

In [59]:
house_price_df=pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')

In [62]:
house_price_df
house_price_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
#do here

# TASK #8: PANDAS OPERATIONS

In [64]:
# Let's define a dataframe as follows:
bank_client_df=pd.DataFrame({'Bank client id': [111,222,333,444,555,6666,777],'Name': ['Ridham','Harman','Vishav','Puneet','Pranav','Indom',"yop"],
                              'marks':[100,67,55,43,78,65,78]
                            })
bank_client_df

Bank client id    Name  marks
0             111  Ridham    100
1             222  Harman     67
2             333  Vishav     55
3             444  Puneet     43
4             555  Pranav     78
5            6666   Indom     65
6             777     yop     78

In [69]:
# Pick certain rows that satisfy a certain criteria 
bank_client_df[bank_client_df['marks']>70]

Bank client id    Name  marks
0             111  Ridham    100
4             555  Pranav     78
6             777     yop     78

In [70]:
# Delete a column from a DataFrame
del bank_client_df['Name']

In [71]:
bank_client_df

Bank client id  marks
0             111    100
1             222     67
2             333     55
3             444     43
4             555     78
5            6666     65
6             777     78

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
# do here

# TASK #9: PANDAS WITH FUNCTIONS

In [73]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [74]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 


def  networth_update(balance):
    return balance*1.2



In [75]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [76]:
def networth_update(balance):
    return balance*3+100

In [77]:
results=bank_client_df['Net worth [$]'].apply(networth_update)

In [78]:
results

0    10600
1    87100
2    30100
3     6100
Name: Net worth [$], dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
# do 

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [81]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                             'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [83]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by='Net worth [$]')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
3             444             Ryan           2000                5
0             111           Chanel           3500                3
2             333            Mitch          10000                9
1             222            Steve          29000                4

In [84]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [86]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by='Net worth [$]',inplace=True)
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
3             444             Ryan           2000                5
0             111           Chanel           3500                3
2             333            Mitch          10000                9
1             222            Steve          29000                4

In [87]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
3             444             Ryan           2000                5
0             111           Chanel           3500                3
2             333            Mitch          10000                9
1             222            Steve          29000                4

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [90]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [92]:
df=pd.DataFrame({'A':['A0','A1','A2','A3'],
                 'B':['B0','B1','B2','B3'],
                 'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']
                },
               index=[0,1,2,3])
df

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [93]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                 'B':['B4','B5','B6','B7'],
                 'C':['C4','C5','C6','C7'],
                 'D':['D4','D5','D6','D7']
                },
               index=[4,5,6,7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7